### ISSUE TITLE
 Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

### ISSUE THREAD

**Issue by tejalal** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#24]
I tried to run the code as instructed in the discussion. The training part is completed but, during inference, it is raising below error. I didn't change anything in the code. Just executing as:

**python detect.py**

 Does anyone have any suggestion

This particular line (model.py file) is raising an error.

**suppress = torch.max(suppress, overlap[box] > max_overlap)**

![error](https://user-images.githubusercontent.com/35481426/65964241-22a6a380-e47a-11e9-8600-3e0d2e99a271.png)

 **Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'**

**Comment by MartinEliasQ** [comment]
Hello @tejalal ,
The problem occurs because the comparison is waiting for scalars but when using ">" you receive a Boolean tensor. I had the same problem with the latest release of Pytorch. I solved it by creating a variable that saves the comparison as Booleans and creating another tensor where the type of data is changed to uint8.
```python
      condition = overlap[box] > max_overlap
      condition = torch.tensor(condition, dtype=torch.uint8).to(device)
      #print(torch.tensor(condition,dtype=torch.uint8))
      suppress = torch.max(suppress, condition)  
```

**Comment by jackson211** [comment]
> Hello @tejalal ,
> The problem occurs because the comparison is waiting for scalars but when using ">" you receive a Boolean tensor. I had the same problem with the latest release of Pytorch. I solved it by creating a variable that saves the comparison as Booleans and creating another tensor where the type of data is changed to uint8.
> 
> ```python
>       condition = overlap[box] > max_overlap
>       condition = torch.tensor(condition, dtype=torch.uint8).to(device)
>       #print(torch.tensor(condition,dtype=torch.uint8))
>       suppress = torch.max(suppress, condition)  
> ```

Hey @MartinEliasQ,  
It gives UserWarning that uint8 is now deprecated, so I initialised suppress to torch.bool dtype and change following operation on suppress to logical operation. It gives no warning now. 

```python
                suppress = torch.zeros((n_above_min_score)).bool().to(device)  # (n_qualified)

                # Consider each box in order of decreasing scores
                for box in range(class_decoded_locs.size(0)):
                    # If this box is already marked for suppression
                    if suppress[box] == 1:
                        continue

                    # Suppress boxes whose overlaps (with this box) are greater than maximum overlap
                    # Find such boxes and update suppress indices
                    suppress = suppress | (overlap[box] > max_overlap)
                    # The max operation retains previously suppressed boxes, like an 'OR' operation

                    # Don't suppress this box, even though it has an overlap of 1 with itself
                    suppress[box] = 0

                # Store only unsuppressed boxes for this class
                image_boxes.append(class_decoded_locs[~suppress])
                image_labels.append(
                    torch.LongTensor(
                        (~suppress).sum().item() * [c]).to(device)
                )
                image_scores.append(class_scores[~suppress])
```

**Comment by 15926273249** [comment]
@jackson211  Do you know how to solve this problem?
Traceback (most recent call last):
  File "eval.py", line 141, in <module>
    evaluate(test_loader, model, test_img_num)
  File "eval.py", line 87, in evaluate
    top_k=200, original_image = images, max_OCR_overlap=0.2, max_OCR_ratio = 0.2)
  File "/ctpn/sroie/sroie/task1/model.py", line 588, in detect_objects
    [original_image.width, original_image.height, original_image.width,
AttributeError: 'Tensor' object has no attribute 'width'

**Comment by aaaaayushh** [comment]
> Hello @tejalal ,
> The problem occurs because the comparison is waiting for scalars but when using ">" you receive a Boolean tensor. I had the same problem with the latest release of Pytorch. I solved it by creating a variable that saves the comparison as Booleans and creating another tensor where the type of data is changed to uint8.
> 
> ```python
>       condition = overlap[box] > max_overlap
>       condition = torch.tensor(condition, dtype=torch.uint8).to(device)
>       #print(torch.tensor(condition,dtype=torch.uint8))
>       suppress = torch.max(suppress, condition)  
> ```

Hey @MartinEliasQ I'm still getting the same error even after trying your solution. Any tips?
