### ISSUE TITLE
CUDA memory increasing when runing eval.py

### ISSUE THREAD

**Issue by StrongerzZ** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#44]
Batch size = 2 
13667*2 images

D:\Anaconda3\envs\pytorch_envs\python.exe E:/NNDL_pytorch/SSD/eval.py
Evaluating:   1%|          | 121/13667 [06:05<18:15:33,  4.85s/it]Traceback (most recent call last):
  File "E:/NNDL_pytorch/SSD/eval.py", line 117, in <module>
    evaluate(test_loader, model)
  File "E:/NNDL_pytorch/SSD/eval.py", line 92, in evaluate
    top_k=200)
  File "E:\NNDL_pytorch\SSD\detect_modules.py", line 74, in detect_objects
    overlap = find_jaccard_overlap(class_decoded_locs, class_decoded_locs)  # (n_qualified, n_qualified)
  File "E:\NNDL_pytorch\SSD\utils.py", line 697, in find_jaccard_overlap
    intersection = find_intersection(set_1, set_2)  # (n1, n2)
  File "E:\NNDL_pytorch\SSD\utils.py", line 681, in find_intersection
    intersection_dims = torch.clamp(upper_bounds - lower_bounds, min=0)  # (n1, n2, 2)
RuntimeError: CUDA out of memory. Tried to allocate 776.00 MiB (GPU 0; 8.00 GiB total capacity; 2.90 GiB already allocated; 32.01 MiB free; 604.85 MiB cached)
Evaluating:   1%|          | 121/13667 [06:07<11:25:33,  3.04s/it]

**Comment by willchao612** [comment]
Seems reducing batch size will suppress this error
