### ISSUE TITLE
eval.py bugs

### ISSUE THREAD

**Issue by AnhNguyenUK** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#57]
Hi, i am facing the problem with the evaluation step to get the mAP scores. The detail of error:
File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\ADMIN\anaconda3\envs\Pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".\a-PyTorch-Tutorial-to-Object-Detection\datasets.py", line 56, in __getitem__
    image, boxes, labels, difficulties = transform(image, boxes, labels, difficulties, split=self.split)
  File ".\a-PyTorch-Tutorial-to-Object-Detection\utils.py", line 705, in transform
    new_image, new_boxes = resize(new_image, new_boxes, dims=(300, 300))
  File ".\a-PyTorch-Tutorial-to-Object-Detection\utils.py", line 616, in resize
    new_boxes = boxes / old_dims  # percent coordinates
RuntimeError: The size of tensor a (0) must match the size of tensor b (4) at non-singleton dimension 1 

Are there any idea? Someone said that this is the bug of torch library, but i am not sure. The training and detect work well.

**Comment by NguyenVanThanhHust** [comment]
This is mean there is (at least) one img in your dataset doesn't contain any bbox.

**Comment by rttariverdi67** [comment]
@NguyenVanThanhHust , @AnhNguyenUK , 
I face with same error, how can I fix it?
thank you

**Comment by NguyenVanThanhHust** [comment]
@rttariverdi67 Did you check your dataset? Is the image creating this error readable?

**Comment by rttariverdi67** [comment]
@NguyenVanThanhHust thank you for your help, It was exactly the problem, The image didn't contain any class! I deleted and it works.
