### ISSUE TITLE
font error running detect.py

### ISSUE THREAD

**Issue by rttariverdi67** [sgrvinod/a-PyTorch-Tutorial-to-Object-Detection#71]
Traceback (most recent call last):
  File "detect.py", line 102, in <module>
    detect(original_image, min_score=0.2, max_overlap=0.5, top_k=200).show()
  File "detect.py", line 67, in detect
    **`_font = ImageFont.truetype("./calibril.ttf", 15)_`**
  File "/home/rahim/anaconda3/lib/python3.7/site-packages/PIL/ImageFont.py", line 642, in truetype
    return freetype(font)
  File "/home/rahim/anaconda3/lib/python3.7/site-packages/PIL/ImageFont.py", line 639, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/rahim/anaconda3/lib/python3.7/site-packages/PIL/ImageFont.py", line 188, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource

**Comment by NiranjanRavi1993** [comment]
Hi,
    Did you resolve the error?

**Comment by rttariverdi67** [comment]
Hi@NiranjanRavi1993, yes, there are two options. easy one in to replace the line with 
*"font = ImageFont.load_default()"*
or second option is to download the font or any which you like and extract it in your directory, [here](https://askubuntu.com/questions/651441/how-to-install-arial-font-and-other-windows-fonts-in-ubuntu/1092920#1092920?newreg=ea20752e451448f5971cb7e1655b466c) is link to get come fonts.

**Comment by NiranjanRavi1993** [comment]
Yes, this fix helped. Thank you.
